# Typus Models Configuration File
#
# Use the README file as a reference to customize settings.

Company:
  fields:
    default: domain, name, image, tag_list
    form: domain, name, image, tag_list
  order_by: 
  relationships: deals, locations, subscriptions
  filters: created_at
  search: name
  application: lumlate

Deal:
  fields:
    default: title, description, maxvalue, expiry, tag_list, company, subscription, deal_type, slug
    form: title, description, maxvalue, expiry, tag_list, company, subscription, deal_type
  order_by: 
  relationships: emails
  filters: created_at
  search: title
  application: lumlate

DealType:
  fields:
    default: name
    form: name
  order_by: 
  relationships: deals
  filters: created_at
  search: name
  application: lumlate

Email:
  fields:
    default: external_id, sent, recieved, from, fromname, to, subject, userdata, user, subscription, deal, email_type
    form: external_id, sent, recieved, from, fromname, to, subject, userdata, user, subscription, deal, email_type
  order_by: 
  relationships:
  filters: created_at
  search: 
  application: lumlate

EmailType:
  fields:
    default: name
    form: name
  order_by: 
  relationships: emails
  filters: created_at
  search: name
  application: lumlate

Location:
  fields:
    default: address, zipcode, city, state, company
    form: address, zipcode, city, state, company
  order_by: 
  relationships:
  filters: created_at
  search: 
  application: lumlate

Subscription:
  fields:
    default: domain, email_domain, url, form_data, submit_method,  title, tag_list, subscription_type, company, slug
    form: domain, email_domain, url, form_data, submit_method, title, tag_list, subscription_type, company
  order_by: 
  relationships: deals, emails, users
  filters: created_at
  search: title
  application: lumlate

SubscriptionStatus:
  fields:
    default: name
    form: name
  order_by:
  relationships: user_subscriptions
  filters: created_at
  search: name
  application: lumlate

SubscriptionType:
  fields:
    default: name
    form: name
  order_by: 
  relationships: subscriptions
  filters: created_at
  search: name
  application: lumlate

User:
  fields:
    default: email, sign_in_count, current_sign_in_at, last_sign_in_at, current_sign_in_ip, last_sign_in_ip, username, role
    form: email, username, role
  order_by: 
  relationships: emails, subscriptions, user_subscriptions
  filters: created_at
  search: 
  application: lumlate
  options:
    read_only:remember_token, sign_in_count, current_sign_in_at, last_sign_in_at, current_sign_in_ip, last_sign_in_ip,

UserSubscription:
  fields:
    default: user_id, subscription_id, subscription_status_id, subscripton_status, user, subscription
    form: user_id, subscription_id, subscription_status_id, subscripton_status, user, subscription
  order_by:
  relationships:
  filters: created_at
  search:
  application: lumlate
