# Typus Models Configuration File
#
# Use the README file as a reference to customize settings.

DealType:
  fields:
    default: name
    form: name
  order_by: 
  relationships: 
  filters: created_at
  search: name
  application: lumlate

EmailType:
  fields:
    default: name
    form: name
  order_by: 
  relationships: 
  filters: created_at
  search: name
  application: lumlate

SubscriptionType:
  fields:
    default: name
    form: name
  order_by: 
  relationships: 
  filters: created_at
  search: name
  application: lumlate

